import {Task_Error, type Task} from '@ryanatkn/gro';
import {z} from 'zod';
import {readFile, writeFile} from 'node:fs/promises';
import {format_file} from '@ryanatkn/gro/format_file.js';
import {basename, resolve} from 'node:path';
import {paths, print_path} from '@ryanatkn/gro/paths.js';
import {load_from_env} from '@ryanatkn/gro/env.js';
import {embed_json} from '@ryanatkn/belt/json.js';
import {load_package_json} from '@ryanatkn/gro/package_json.js';
import {existsSync} from 'node:fs';

import {load_gitops_config} from '$lib/gitops_config.js';
import {fetch_repos} from '$lib/fetch_repos.js';
import {create_fs_fetch_value_cache} from '$lib/fs_fetch_value_cache.js';
import {resolve_gitops_config} from '$lib/resolve_gitops_config.js';

// TODO add flag to ignore or invalidate cache -- no-cache? clean?

// TODO maybe support `--check` for CI
export const Args = z
	.object({
		path: z.string({description: 'path to the fuz config file'}).default('gitops.config.ts'),
		dir: z.string({description: 'path to the repos directory'}).default(paths.root),
		outdir: z
			.string({description: 'path to the directory for the generated files, defaults to $routes/'})
			.optional(),
	})
	.strict();
export type Args = z.infer<typeof Args>;

/**
 * This is a task not a `.gen.` file because it makes network calls.
 */
export const task: Task<Args> = {
	Args,
	summary: 'download metadata for the given repos',
	run: async ({args, log, sveltekit_config}) => {
		const {path, dir, outdir = sveltekit_config.routes_path} = args;

		const outfile = resolve(outdir, 'repos.ts');

		const gitops_config = await load_gitops_config(path, dir);

		const cache = await create_fs_fetch_value_cache('repos');

		// This searches the parent directory for the env var, so we don't use SvelteKit's $env imports
		const token = load_from_env('GITHUB_TOKEN_SECRET');
		if (!token) {
			log.warn('the env var GITHUB_TOKEN_SECRET was not found, so API calls with be unauthorized');
		}

		const resolved_gitops_config = resolve_gitops_config(gitops_config);
		console.log(`resolved_gitops_config`, resolved_gitops_config);
		const {resolved_local_repos, unresolved_local_repos} = resolved_gitops_config;

		if (unresolved_local_repos) {
			log.error(
				'Failed to resolve local configs - do you need to fetch them or configure the directory?',
				unresolved_local_repos.map((r) => r.repo_url),
			);
			throw new Task_Error('Failed to resolve local configs');
		}
		if (!resolved_local_repos) {
			throw new Task_Error('No repos are configured in `gitops_config.ts`');
		}

		const fetched_repos = await fetch_repos(resolved_local_repos, token, cache.data, dir, log);
		console.log(`fetched_repos`, fetched_repos);
		return;

		// TODO should package_json be provided in the Gro task/gen contexts? check if it's always loaded
		const package_json = load_package_json(dir);
		const specifier =
			package_json.name === '@ryanatkn/fuz_gitops'
				? '$lib/repo.js'
				: '@ryanatkn/fuz_gitops/repo.js';

		// JSON is faster to parse than JS so we optimize it by embedding the data as a string.
		// TODO the `basename` is used here because we don't have an `origin_id` like with gen,
		// and this file gets re-exported,
		// and we don't want the file to change based on where it's being generated,
		// because for example linking to a local package would change the contents
		const contents = `
			// generated by ${basename(import.meta.filename)}
			import type {Repo} from '${specifier}';

			export const repos: Repo[] = ${embed_json(fetched_repos, (s) => JSON.stringify(s, null, '\t'))};
		`;
		// TODO think about possibly using the `gen` functionality in this task, not sure what the API design could look like
		const formatted = await format_file(contents, {filepath: outfile});
		const existing = existsSync(outfile) ? await readFile(outfile, 'utf8') : '';
		if (existing === formatted) {
			log.info(`no changes to ${print_path(outfile)}`);
		} else {
			log.info(`writing changes to ${print_path(outfile)}`);
			await writeFile(outfile, formatted);
		}

		const changed = await cache.save();
		if (changed) {
			log.info('repos cache updated');
		} else {
			log.info('repos cache did not change');
		}
	},
};
