// generated by gitops.task.ts
import type {Repo} from '$lib/repo.js';

export const repos: Array<Repo> = JSON.parse(
	'[\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz",\
			"version": "0.147.0",\
			"description": "Svelte UI library",\
			"motto": "friendly user zystem",\
			"glyph": "🧶",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly brown spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://www.fuz.dev/",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"repository": {\
				"type": "git",\
				"url": "git+https://github.com/ryanatkn/fuz.git"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": "*",\
				"@ryanatkn/gro": ">=0.165.0",\
				"@ryanatkn/moss": "*",\
				"@sveltejs/kit": "^2.26",\
				"esm-env": "^1",\
				"svelte": "^5"\
			},\
			"peerDependenciesMeta": {\
				"@ryanatkn/gro": {\
					"optional": true\
				},\
				"esm-env": {\
					"optional": true\
				}\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.34.1",\
				"@ryanatkn/eslint-config": "^0.8.0",\
				"@ryanatkn/fuz_code": "^0.26.0",\
				"@ryanatkn/gro": "^0.167.1",\
				"@ryanatkn/moss": "^0.36.0",\
				"@sveltejs/adapter-static": "^3.0.9",\
				"@sveltejs/kit": "^2.37.0",\
				"@sveltejs/package": "^2.5.0",\
				"@sveltejs/vite-plugin-svelte": "^6.1.3",\
				"@types/node": "^24.3.0",\
				"@types/prismjs": "^1.26.5",\
				"eslint": "^9.34.0",\
				"eslint-plugin-svelte": "^3.11.0",\
				"esm-env": "^1.2.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"prism-svelte": "^0.5.0",\
				"prismjs": "^1.30.0",\
				"svelte": "^5.38.6",\
				"svelte-check": "^4.3.1",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.2",\
				"typescript-eslint": "^8.41.0",\
				"vitest": "^3.2.4"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz",\
			"version": "0.147.0",\
			"modules": {\
				"./alert.js": {\
					"path": "alert.ts",\
					"declarations": [\
						{\
							"name": "Alert_Status",\
							"kind": "type"\
						},\
						{\
							"name": "Alert_Status_Options",\
							"kind": "type"\
						},\
						{\
							"name": "alert_status_options",\
							"kind": "variable"\
						}\
					]\
				},\
				"./constants.js": {\
					"path": "constants.ts",\
					"declarations": [\
						{\
							"name": "MAIN_HEADER_MARGIN_TOP",\
							"kind": "variable"\
						}\
					]\
				},\
				"./context_helpers.js": {\
					"path": "context_helpers.ts",\
					"declarations": [\
						{\
							"name": "create_context",\
							"kind": "function"\
						}\
					]\
				},\
				"./contextmenu_state.svelte.js": {\
					"path": "contextmenu_state.svelte.ts",\
					"declarations": [\
						{\
							"name": "Contextmenu_Params",\
							"kind": "type"\
						},\
						{\
							"name": "Item_State",\
							"kind": "type"\
						},\
						{\
							"name": "Entry_State",\
							"kind": "class"\
						},\
						{\
							"name": "Submenu_State",\
							"kind": "class"\
						},\
						{\
							"name": "Root_Menu_State",\
							"kind": "class"\
						},\
						{\
							"name": "Contextmenu_Run",\
							"kind": "type"\
						},\
						{\
							"name": "Contextmenu_State_Options",\
							"kind": "type"\
						},\
						{\
							"name": "Contextmenu_State",\
							"kind": "class"\
						},\
						{\
							"name": "contextmenu_action",\
							"kind": "function"\
						},\
						{\
							"name": "open_contextmenu",\
							"kind": "function"\
						},\
						{\
							"name": "contextmenu_context",\
							"kind": "variable"\
						},\
						{\
							"name": "contextmenu_submenu_context",\
							"kind": "variable"\
						},\
						{\
							"name": "contextmenu_dimensions_context",\
							"kind": "variable"\
						}\
					]\
				},\
				"./csp_of_ryanatkn.js": {\
					"path": "csp_of_ryanatkn.ts",\
					"declarations": [\
						{\
							"name": "csp_trusted_sources_of_ryanatkn",\
							"kind": "variable"\
						}\
					]\
				},\
				"./csp.js": {\
					"path": "csp.ts",\
					"declarations": [\
						{\
							"name": "create_csp_directives",\
							"kind": "function"\
						},\
						{\
							"name": "Create_Csp_Directives_Options",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Directive",\
							"kind": "type"\
						},\
						{\
							"name": "parse_csp_directive",\
							"kind": "function"\
						},\
						{\
							"name": "Csp_Directive_Value",\
							"kind": "type"\
						},\
						{\
							"name": "csp_trust_levels",\
							"kind": "variable"\
						},\
						{\
							"name": "csp_trust_level_value",\
							"kind": "variable"\
						},\
						{\
							"name": "Csp_Trust_Level",\
							"kind": "type"\
						},\
						{\
							"name": "parse_csp_trust_level",\
							"kind": "function"\
						},\
						{\
							"name": "Csp_Source_Spec",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Directive_Spec",\
							"kind": "type"\
						},\
						{\
							"name": "is_csp_trusted",\
							"kind": "function"\
						},\
						{\
							"name": "COLOR_SCHEME_SCRIPT_HASH",\
							"kind": "variable"\
						},\
						{\
							"name": "csp_directive_value_defaults",\
							"kind": "variable"\
						},\
						{\
							"name": "csp_directive_required_trust_defaults",\
							"kind": "variable"\
						},\
						{\
							"name": "csp_directive_specs",\
							"kind": "variable"\
						},\
						{\
							"name": "csp_directive_spec_by_name",\
							"kind": "variable"\
						},\
						{\
							"name": "Csp_Action_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Base_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Crypto_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Frame_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Host_Name_Scheme",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Host_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Host_Protocol_Schemes",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Port_Scheme",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Scheme_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Source",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Sources",\
							"kind": "type"\
						},\
						{\
							"name": "Csp_Directives",\
							"kind": "type"\
						}\
					]\
				},\
				"./dialog.js": {\
					"path": "dialog.ts",\
					"declarations": [\
						{\
							"name": "to_dialog_params",\
							"kind": "function"\
						},\
						{\
							"name": "Dialog_Params",\
							"kind": "type"\
						},\
						{\
							"name": "Dialog_Layout",\
							"kind": "type"\
						},\
						{\
							"name": "dialog_layouts",\
							"kind": "variable"\
						}\
					]\
				},\
				"./dimensions.svelte.js": {\
					"path": "dimensions.svelte.ts",\
					"declarations": [\
						{\
							"name": "Dimensions",\
							"kind": "class"\
						}\
					]\
				},\
				"./docs_helpers.svelte.js": {\
					"path": "docs_helpers.svelte.ts",\
					"declarations": [\
						{\
							"name": "DEFAULT_LIBRARY_PATH",\
							"kind": "variable"\
						},\
						{\
							"name": "to_docs_path_info",\
							"kind": "function"\
						},\
						{\
							"name": "docs_links_context",\
							"kind": "variable"\
						},\
						{\
							"name": "Docs_Link_Tag",\
							"kind": "type"\
						},\
						{\
							"name": "Docs_Link",\
							"kind": "type"\
						},\
						{\
							"name": "Docs_Links",\
							"kind": "class"\
						}\
					]\
				},\
				"./helpers.js": {\
					"path": "helpers.ts",\
					"declarations": [\
						{\
							"name": "render_value_to_string",\
							"kind": "function"\
						}\
					]\
				},\
				"./intersect.js": {\
					"path": "intersect.ts",\
					"declarations": [\
						{\
							"name": "Intersect_Params",\
							"kind": "type"\
						},\
						{\
							"name": "Intersect_Params_Or_Callback",\
							"kind": "type"\
						},\
						{\
							"name": "intersect",\
							"kind": "function"\
						},\
						{\
							"name": "On_Intersect",\
							"kind": "type"\
						},\
						{\
							"name": "Intersect_State",\
							"kind": "type"\
						},\
						{\
							"name": "On_Disconnect",\
							"kind": "type"\
						},\
						{\
							"name": "Disconnect_State",\
							"kind": "type"\
						}\
					]\
				},\
				"./logos.js": {\
					"path": "logos.ts",\
					"declarations": [\
						{\
							"name": "zzz_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "gro_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "fuz_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "moss_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "belt_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "fuz_code_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "fuz_blog_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "fuz_mastodon_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "fuz_gitops_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "fuz_template_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "webdevladder_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "earbetter_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "spiderspace_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "github_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "mdn_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "chatgpt_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "claude_logo",\
							"kind": "variable"\
						},\
						{\
							"name": "gemini_logo",\
							"kind": "variable"\
						}\
					]\
				},\
				"./pkg.js": {\
					"path": "pkg.ts",\
					"declarations": [\
						{\
							"name": "pkg_context",\
							"kind": "variable"\
						}\
					]\
				},\
				"./rune_helpers.svelte.js": {\
					"path": "rune_helpers.svelte.ts",\
					"declarations": [\
						{\
							"name": "effect_with_count",\
							"kind": "function"\
						}\
					]\
				},\
				"./storage.js": {\
					"path": "storage.ts",\
					"declarations": [\
						{\
							"name": "save_to_storage",\
							"kind": "function"\
						},\
						{\
							"name": "load_from_storage",\
							"kind": "function"\
						}\
					]\
				},\
				"./themer.svelte.js": {\
					"path": "themer.svelte.ts",\
					"declarations": [\
						{\
							"name": "Themer",\
							"kind": "class"\
						},\
						{\
							"name": "Themer_Json",\
							"kind": "type"\
						},\
						{\
							"name": "themer_context",\
							"kind": "variable"\
						},\
						{\
							"name": "sync_color_scheme",\
							"kind": "function"\
						},\
						{\
							"name": "COLOR_SCHEME_STORAGE_KEY",\
							"kind": "variable"\
						},\
						{\
							"name": "THEME_STORAGE_KEY",\
							"kind": "variable"\
						},\
						{\
							"name": "save_color_scheme",\
							"kind": "function"\
						},\
						{\
							"name": "load_color_scheme",\
							"kind": "function"\
						},\
						{\
							"name": "save_theme",\
							"kind": "function"\
						},\
						{\
							"name": "load_theme",\
							"kind": "function"\
						}\
					]\
				},\
				"./tome.js": {\
					"path": "tome.ts",\
					"declarations": [\
						{\
							"name": "Tome",\
							"kind": "variable"\
						},\
						{\
							"name": "to_tome_pathname",\
							"kind": "function"\
						},\
						{\
							"name": "tomes_context",\
							"kind": "variable"\
						},\
						{\
							"name": "get_tome_by_name",\
							"kind": "function"\
						},\
						{\
							"name": "tome_context",\
							"kind": "variable"\
						}\
					]\
				},\
				"./Alert.svelte": {\
					"path": "Alert.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Breadcrumb.svelte": {\
					"path": "Breadcrumb.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Card.svelte": {\
					"path": "Card.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Color_Scheme_Input.svelte": {\
					"path": "Color_Scheme_Input.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Community_Links_Panel.svelte": {\
					"path": "Community_Links_Panel.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Community_Links.svelte": {\
					"path": "Community_Links.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Contextmenu_Entry.svelte": {\
					"path": "Contextmenu_Entry.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Contextmenu_Link_Entry.svelte": {\
					"path": "Contextmenu_Link_Entry.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Contextmenu_Root.svelte": {\
					"path": "Contextmenu_Root.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Contextmenu_Submenu.svelte": {\
					"path": "Contextmenu_Submenu.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Contextmenu_Text_Entry.svelte": {\
					"path": "Contextmenu_Text_Entry.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Contextmenu.svelte": {\
					"path": "Contextmenu.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Copy_To_Clipboard.svelte": {\
					"path": "Copy_To_Clipboard.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Details.svelte": {\
					"path": "Details.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Dialog.svelte": {\
					"path": "Dialog.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Dialogs.svelte": {\
					"path": "Dialogs.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Content.svelte": {\
					"path": "Docs_Content.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Footer.svelte": {\
					"path": "Docs_Footer.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Menu_Header.svelte": {\
					"path": "Docs_Menu_Header.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Menu.svelte": {\
					"path": "Docs_Menu.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Page_Links.svelte": {\
					"path": "Docs_Page_Links.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Primary_Nav.svelte": {\
					"path": "Docs_Primary_Nav.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Secondary_Nav.svelte": {\
					"path": "Docs_Secondary_Nav.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs_Tertiary_Nav.svelte": {\
					"path": "Docs_Tertiary_Nav.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Docs.svelte": {\
					"path": "Docs.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Hashlink.svelte": {\
					"path": "Hashlink.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Hidden_Personal_Links.svelte": {\
					"path": "Hidden_Personal_Links.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Hue_Input.svelte": {\
					"path": "Hue_Input.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Identifier.svelte": {\
					"path": "Identifier.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Img_Or_Svg.svelte": {\
					"path": "Img_Or_Svg.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Mdn_Link.svelte": {\
					"path": "Mdn_Link.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Package_Detail.svelte": {\
					"path": "Package_Detail.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Package_Summary.svelte": {\
					"path": "Package_Summary.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Paste_From_Clipboard.svelte": {\
					"path": "Paste_From_Clipboard.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Pending_Animation.svelte": {\
					"path": "Pending_Animation.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Pending_Button.svelte": {\
					"path": "Pending_Button.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Project_Links.svelte": {\
					"path": "Project_Links.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Redirect.svelte": {\
					"path": "Redirect.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Spiders.svelte": {\
					"path": "Spiders.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Svg.svelte": {\
					"path": "Svg.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Teleport.svelte": {\
					"path": "Teleport.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Theme_Input.svelte": {\
					"path": "Theme_Input.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Themed.svelte": {\
					"path": "Themed.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tome_Content.svelte": {\
					"path": "Tome_Content.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tome_Header.svelte": {\
					"path": "Tome_Header.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tome_Link.svelte": {\
					"path": "Tome_Link.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tome_Section_Header.svelte": {\
					"path": "Tome_Section_Header.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tome_Section.svelte": {\
					"path": "Tome_Section.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				}\
			}\
		},\
		"name": "@ryanatkn/fuz",\
		"repo_name": "fuz",\
		"repo_url": "https://github.com/ryanatkn/fuz",\
		"owner_name": "ryanatkn",\
		"homepage_url": "https://www.fuz.dev/",\
		"logo_url": "https://www.fuz.dev/logo.svg",\
		"logo_alt": "a friendly brown spider facing you",\
		"npm_url": "https://www.npmjs.com/package/@ryanatkn/fuz",\
		"changelog_url": "https://github.com/ryanatkn/fuz/blob/main/CHANGELOG.md",\
		"published": true,\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": [\
			{\
				"number": 71,\
				"title": "use the `dialog` element in `Dialog`",\
				"user": {\
					"login": "ryanatkn"\
				},\
				"draft": true\
			}\
		]\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_template",\
			"version": "0.0.1",\
			"description": "a static web app and Node library template with TypeScript, Svelte, SvelteKit, Vite, esbuild, Gro, and Fuz",\
			"glyph": "❄",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly pixelated spider facing you",\
			"public": true,\
			"homepage": "https://template.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_template",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"devDependencies": {\
				"@ryanatkn/belt": "^0.34.1",\
				"@ryanatkn/eslint-config": "^0.8.0",\
				"@ryanatkn/fuz": "^0.147.0",\
				"@ryanatkn/gro": "^0.167.1",\
				"@ryanatkn/moss": "^0.36.0",\
				"@sveltejs/adapter-static": "^3.0.9",\
				"@sveltejs/kit": "^2.37.1",\
				"@sveltejs/vite-plugin-svelte": "^6.1.4",\
				"eslint": "^9.35.0",\
				"eslint-plugin-svelte": "^3.12.1",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.38.7",\
				"svelte-check": "^4.3.1",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.2",\
				"typescript-eslint": "^8.42.0",\
				"vitest": "^3.2.4"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist"\
			]\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_template",\
			"version": "0.0.1"\
		},\
		"name": "@ryanatkn/fuz_template",\
		"repo_name": "fuz_template",\
		"repo_url": "https://github.com/ryanatkn/fuz_template",\
		"owner_name": "ryanatkn",\
		"homepage_url": "https://template.fuz.dev/",\
		"logo_url": "https://template.fuz.dev/logo.svg",\
		"logo_alt": "a friendly pixelated spider facing you",\
		"npm_url": null,\
		"changelog_url": null,\
		"published": false,\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_gitops",\
			"version": "0.50.0",\
			"description": "a tool for managing many repos",\
			"glyph": "🪄",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly blue spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://gitops.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_gitops",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz_gitops/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": "*",\
				"@ryanatkn/fuz": "*",\
				"@ryanatkn/gro": "*",\
				"@ryanatkn/moss": "*",\
				"@sveltejs/kit": "^2",\
				"svelte": "^5",\
				"zod": "^4.1.5"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.34.1",\
				"@ryanatkn/eslint-config": "^0.8.0",\
				"@ryanatkn/fuz": "^0.147.0",\
				"@ryanatkn/gro": "^0.167.1",\
				"@ryanatkn/moss": "^0.36.0",\
				"@sveltejs/adapter-static": "^3.0.9",\
				"@sveltejs/kit": "^2.37.1",\
				"@sveltejs/package": "^2.5.0",\
				"@sveltejs/vite-plugin-svelte": "^6.1.4",\
				"@types/node": "^24.3.1",\
				"eslint": "^9.35.0",\
				"eslint-plugin-svelte": "^3.12.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.38.7",\
				"svelte-check": "^4.3.1",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.2",\
				"typescript-eslint": "^8.42.0",\
				"vitest": "^3.2.4"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_gitops",\
			"version": "0.50.0",\
			"modules": {\
				"./fetch_repo_data.js": {\
					"path": "fetch_repo_data.ts",\
					"declarations": [\
						{\
							"name": "fetch_repo_data",\
							"kind": "function"\
						},\
						{\
							"name": "fetch_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "fetch_src_json",\
							"kind": "function"\
						}\
					]\
				},\
				"./fs_fetch_value_cache.js": {\
					"path": "fs_fetch_value_cache.ts",\
					"declarations": [\
						{\
							"name": "Fetch_Cache",\
							"kind": "type"\
						},\
						{\
							"name": "create_fs_fetch_value_cache",\
							"kind": "function"\
						}\
					]\
				},\
				"./github_helpers.js": {\
					"path": "github_helpers.ts",\
					"declarations": [\
						{\
							"name": "Filter_Pull_Request",\
							"kind": "type"\
						},\
						{\
							"name": "Pull_Request_Meta",\
							"kind": "type"\
						},\
						{\
							"name": "to_pull_requests",\
							"kind": "function"\
						},\
						{\
							"name": "to_pull_url",\
							"kind": "function"\
						}\
					]\
				},\
				"./github.js": {\
					"path": "github.ts",\
					"declarations": [\
						{\
							"name": "Github_Pull_Request",\
							"kind": "variable"\
						},\
						{\
							"name": "Github_Pull_Requests",\
							"kind": "variable"\
						},\
						{\
							"name": "fetch_github_pull_requests",\
							"kind": "function"\
						},\
						{\
							"name": "Github_Check_Runs_Item",\
							"kind": "variable"\
						},\
						{\
							"name": "Github_Check_Runs",\
							"kind": "variable"\
						},\
						{\
							"name": "fetch_github_check_runs",\
							"kind": "function"\
						}\
					]\
				},\
				"./gitops_config.js": {\
					"path": "gitops_config.ts",\
					"declarations": [\
						{\
							"name": "Gitops_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Gitops_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gitops_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Gitops_Repo_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gitops_Repo_Config",\
							"kind": "type"\
						},\
						{\
							"name": "create_empty_gitops_config",\
							"kind": "function"\
						},\
						{\
							"name": "normalize_gitops_config",\
							"kind": "function"\
						},\
						{\
							"name": "Gitops_Config_Module",\
							"kind": "type"\
						},\
						{\
							"name": "load_gitops_config",\
							"kind": "function"\
						},\
						{\
							"name": "validate_gitops_config_module",\
							"kind": "function"\
						}\
					]\
				},\
				"./gitops_ready.task.js": {\
					"path": "gitops_ready.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./gitops_task_helpers.js": {\
					"path": "gitops_task_helpers.ts",\
					"declarations": [\
						{\
							"name": "get_gitops_ready",\
							"kind": "function"\
						},\
						{\
							"name": "resolve_gitops_paths",\
							"kind": "function"\
						},\
						{\
							"name": "import_gitops_config",\
							"kind": "function"\
						}\
					]\
				},\
				"./gitops.task.js": {\
					"path": "gitops.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./local_repo.js": {\
					"path": "local_repo.ts",\
					"declarations": [\
						{\
							"name": "Local_Repo",\
							"kind": "type"\
						},\
						{\
							"name": "Maybe_Local_Repo",\
							"kind": "type"\
						},\
						{\
							"name": "Resolved_Local_Repo",\
							"kind": "type"\
						},\
						{\
							"name": "Unresolved_Local_Repo",\
							"kind": "type"\
						},\
						{\
							"name": "load_local_repo",\
							"kind": "function"\
						},\
						{\
							"name": "load_local_repos",\
							"kind": "function"\
						},\
						{\
							"name": "resolve_local_repo",\
							"kind": "function"\
						}\
					]\
				},\
				"./repo.js": {\
					"path": "repo.ts",\
					"declarations": [\
						{\
							"name": "Repo",\
							"kind": "type"\
						},\
						{\
							"name": "Repos",\
							"kind": "type"\
						},\
						{\
							"name": "repos_context",\
							"kind": "variable"\
						},\
						{\
							"name": "parse_repos",\
							"kind": "function"\
						}\
					]\
				},\
				"./resolved_gitops_config.js": {\
					"path": "resolved_gitops_config.ts",\
					"declarations": [\
						{\
							"name": "Resolved_Gitops_Config",\
							"kind": "type"\
						},\
						{\
							"name": "resolve_gitops_config",\
							"kind": "function"\
						}\
					]\
				},\
				"./Modules_Detail.svelte": {\
					"path": "Modules_Detail.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Modules_Nav.svelte": {\
					"path": "Modules_Nav.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Modules_Page.svelte": {\
					"path": "Modules_Page.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Page_Footer.svelte": {\
					"path": "Page_Footer.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Page_Header.svelte": {\
					"path": "Page_Header.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Pull_Requests_Detail.svelte": {\
					"path": "Pull_Requests_Detail.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Pull_Requests_Page.svelte": {\
					"path": "Pull_Requests_Page.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Repos_Table.svelte": {\
					"path": "Repos_Table.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Repos_Tree_Nav.svelte": {\
					"path": "Repos_Tree_Nav.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Repos_Tree.svelte": {\
					"path": "Repos_Tree.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Table_Page.svelte": {\
					"path": "Table_Page.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tree_Item_Page.svelte": {\
					"path": "Tree_Item_Page.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Tree_Page.svelte": {\
					"path": "Tree_Page.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				}\
			}\
		},\
		"name": "@ryanatkn/fuz_gitops",\
		"repo_name": "fuz_gitops",\
		"repo_url": "https://github.com/ryanatkn/fuz_gitops",\
		"owner_name": "ryanatkn",\
		"homepage_url": "https://gitops.fuz.dev/",\
		"logo_url": "https://gitops.fuz.dev/logo.svg",\
		"logo_alt": "a friendly blue spider facing you",\
		"npm_url": "https://www.npmjs.com/package/@ryanatkn/fuz_gitops",\
		"changelog_url": "https://github.com/ryanatkn/fuz_gitops/blob/main/CHANGELOG.md",\
		"published": true,\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": [\
			{\
				"number": 33,\
				"title": "improve local sync",\
				"user": {\
					"login": "ryanatkn"\
				},\
				"draft": false\
			}\
		]\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_code",\
			"version": "0.26.0",\
			"description": "syntax styling utilities and components for TypeScript, Svelte, SvelteKit",\
			"glyph": "🎨",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly pink spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://code.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_code",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz_code/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy",\
				"benchmark": "gro run benchmark/run_benchmarks.ts",\
				"benchmark-compare": "gro run benchmark/compare/run_compare.ts",\
				"update-generated-fixtures": "gro src/fixtures/update"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/moss": "*",\
				"svelte": "^5"\
			},\
			"peerDependenciesMeta": {\
				"@ryanatkn/moss": {\
					"optional": true\
				},\
				"svelte": {\
					"optional": true\
				}\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.34.1",\
				"@ryanatkn/eslint-config": "^0.8.0",\
				"@ryanatkn/fuz": "^0.147.0",\
				"@ryanatkn/gro": "^0.167.1",\
				"@ryanatkn/moss": "^0.36.0",\
				"@sveltejs/adapter-static": "^3.0.9",\
				"@sveltejs/kit": "^2.37.1",\
				"@sveltejs/package": "^2.5.0",\
				"@sveltejs/vite-plugin-svelte": "^6.1.4",\
				"@types/node": "^24.3.1",\
				"eslint": "^9.35.0",\
				"eslint-plugin-svelte": "^3.12.1",\
				"esm-env": "^1.2.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"svelte": "^5.38.7",\
				"svelte-check": "^4.3.1",\
				"tinybench": "^5.0.1",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.2",\
				"typescript-eslint": "^8.42.0",\
				"vitest": "^3.2.4"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					},\
					{\
						"files": "src/fixtures/generated/**",\
						"options": {\
							"requirePragma": true\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				},\
				"./*.json": {\
					"types": "./dist/*.json.d.ts",\
					"default": "./dist/*.json"\
				},\
				"./*.css": {\
					"default": "./dist/*.css"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_code",\
			"version": "0.26.0",\
			"modules": {\
				"./code_sample.js": {\
					"path": "code_sample.ts",\
					"declarations": [\
						{\
							"name": "Code_Sample",\
							"kind": "type"\
						},\
						{\
							"name": "sample_langs",\
							"kind": "variable"\
						},\
						{\
							"name": "Sample_Lang",\
							"kind": "type"\
						}\
					]\
				},\
				"./grammar_clike.js": {\
					"path": "grammar_clike.ts",\
					"declarations": [\
						{\
							"name": "class_keywords",\
							"kind": "variable"\
						},\
						{\
							"name": "add_grammar_clike",\
							"kind": "function"\
						}\
					]\
				},\
				"./grammar_css.js": {\
					"path": "grammar_css.ts",\
					"declarations": [\
						{\
							"name": "add_grammar_css",\
							"kind": "function"\
						}\
					]\
				},\
				"./grammar_js.js": {\
					"path": "grammar_js.ts",\
					"declarations": [\
						{\
							"name": "add_grammar_js",\
							"kind": "function"\
						}\
					]\
				},\
				"./grammar_json.js": {\
					"path": "grammar_json.ts",\
					"declarations": [\
						{\
							"name": "add_grammar_json",\
							"kind": "function"\
						}\
					]\
				},\
				"./grammar_markup.js": {\
					"path": "grammar_markup.ts",\
					"declarations": [\
						{\
							"name": "add_grammar_markup",\
							"kind": "function"\
						},\
						{\
							"name": "grammar_markup_add_inlined",\
							"kind": "function"\
						},\
						{\
							"name": "grammar_markup_add_attribute",\
							"kind": "function"\
						}\
					]\
				},\
				"./grammar_svelte.js": {\
					"path": "grammar_svelte.ts",\
					"declarations": [\
						{\
							"name": "add_grammar_svelte",\
							"kind": "function"\
						},\
						{\
							"name": "grammar_svelte_add_inlined",\
							"kind": "function"\
						}\
					]\
				},\
				"./grammar_ts.js": {\
					"path": "grammar_ts.ts",\
					"declarations": [\
						{\
							"name": "add_grammar_ts",\
							"kind": "function"\
						}\
					]\
				},\
				"./highlight_manager.js": {\
					"path": "highlight_manager.ts",\
					"declarations": [\
						{\
							"name": "Highlight_Mode",\
							"kind": "type"\
						},\
						{\
							"name": "supports_css_highlight_api",\
							"kind": "function"\
						},\
						{\
							"name": "Highlight_Manager",\
							"kind": "class"\
						}\
					]\
				},\
				"./highlight_priorities.gen.js": {\
					"path": "highlight_priorities.gen.ts",\
					"declarations": [\
						{\
							"name": "gen",\
							"kind": "variable"\
						}\
					]\
				},\
				"./highlight_priorities.js": {\
					"path": "highlight_priorities.ts",\
					"declarations": [\
						{\
							"name": "Highlight_Token_Name",\
							"kind": "type"\
						},\
						{\
							"name": "highlight_priorities",\
							"kind": "variable"\
						}\
					]\
				},\
				"./syntax_styler_global.js": {\
					"path": "syntax_styler_global.ts",\
					"declarations": [\
						{\
							"name": "syntax_styler_global",\
							"kind": "variable"\
						}\
					]\
				},\
				"./syntax_styler.js": {\
					"path": "syntax_styler.ts",\
					"declarations": [\
						{\
							"name": "Add_Syntax_Grammar",\
							"kind": "type"\
						},\
						{\
							"name": "Syntax_Styler",\
							"kind": "class"\
						},\
						{\
							"name": "Syntax_Grammar_Value",\
							"kind": "type"\
						},\
						{\
							"name": "Syntax_Grammar",\
							"kind": "type"\
						},\
						{\
							"name": "Syntax_Grammar_Token",\
							"kind": "type"\
						},\
						{\
							"name": "Hook_Before_Tokenize_Callback",\
							"kind": "type"\
						},\
						{\
							"name": "Hook_After_Tokenize_Callback",\
							"kind": "type"\
						},\
						{\
							"name": "Hook_Wrap_Callback",\
							"kind": "type"\
						},\
						{\
							"name": "Hook_Before_Tokenize_Callback_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Hook_After_Tokenize_Callback_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Hook_Wrap_Callback_Context",\
							"kind": "type"\
						}\
					]\
				},\
				"./syntax_token.js": {\
					"path": "syntax_token.ts",\
					"declarations": [\
						{\
							"name": "Syntax_Token",\
							"kind": "class"\
						},\
						{\
							"name": "Syntax_Token_Stream",\
							"kind": "type"\
						}\
					]\
				},\
				"./tokenize_syntax.js": {\
					"path": "tokenize_syntax.ts",\
					"declarations": [\
						{\
							"name": "tokenize_syntax",\
							"kind": "function"\
						}\
					]\
				},\
				"./Code.svelte": {\
					"path": "Code.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./theme_variables.css": {\
					"path": "theme_variables.css",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "css"\
						}\
					]\
				},\
				"./theme.css": {\
					"path": "theme.css",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "css"\
						}\
					]\
				}\
			}\
		},\
		"name": "@ryanatkn/fuz_code",\
		"repo_name": "fuz_code",\
		"repo_url": "https://github.com/ryanatkn/fuz_code",\
		"owner_name": "ryanatkn",\
		"homepage_url": "https://code.fuz.dev/",\
		"logo_url": "https://code.fuz.dev/logo.svg",\
		"logo_alt": "a friendly pink spider facing you",\
		"npm_url": "https://www.npmjs.com/package/@ryanatkn/fuz_code",\
		"changelog_url": "https://github.com/ryanatkn/fuz_code/blob/main/CHANGELOG.md",\
		"published": true,\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/fuz_mastodon",\
			"version": "0.32.0",\
			"description": "Mastodon components and helpers for Svelte, SvelteKit, and Fuz",\
			"glyph": "🦣",\
			"logo": "logo.svg",\
			"logo_alt": "a friendly purple spider facing you",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://mastodon.fuz.dev/",\
			"repository": "https://github.com/ryanatkn/fuz_mastodon",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"bugs": "https://github.com/ryanatkn/fuz_mastodon/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"peerDependencies": {\
				"@ryanatkn/belt": "*",\
				"@ryanatkn/fuz": "*",\
				"@ryanatkn/moss": "*",\
				"@sveltejs/kit": "^2",\
				"date-fns": "^4",\
				"esm-env": "^1",\
				"svelte": "^5"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@ryanatkn/belt": "^0.34.1",\
				"@ryanatkn/eslint-config": "^0.8.0",\
				"@ryanatkn/fuz": "^0.147.0",\
				"@ryanatkn/fuz_code": "^0.26.0",\
				"@ryanatkn/gro": "^0.167.1",\
				"@ryanatkn/moss": "^0.36.0",\
				"@sveltejs/adapter-static": "^3.0.9",\
				"@sveltejs/kit": "^2.37.1",\
				"@sveltejs/package": "^2.5.0",\
				"@sveltejs/vite-plugin-svelte": "^6.1.4",\
				"date-fns": "^4.1.0",\
				"eslint": "^9.35.0",\
				"eslint-plugin-svelte": "^3.12.2",\
				"esm-env": "^1.2.2",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"prism-svelte": "^0.5.0",\
				"prismjs": "^1.30.0",\
				"svelte": "^5.38.7",\
				"svelte-check": "^4.3.1",\
				"tslib": "^2.8.1",\
				"typescript": "^5.9.2",\
				"typescript-eslint": "^8.42.0",\
				"vitest": "^3.2.4"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				},\
				"./*.svelte": {\
					"types": "./dist/*.svelte.d.ts",\
					"svelte": "./dist/*.svelte",\
					"default": "./dist/*.svelte"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/fuz_mastodon",\
			"version": "0.32.0",\
			"modules": {\
				"./mastodon_cache.svelte.js": {\
					"path": "mastodon_cache.svelte.ts",\
					"declarations": [\
						{\
							"name": "Mastodon_Cache",\
							"kind": "class"\
						},\
						{\
							"name": "mastodon_cache_context",\
							"kind": "variable"\
						}\
					]\
				},\
				"./mastodon.js": {\
					"path": "mastodon.ts",\
					"declarations": [\
						{\
							"name": "to_mastodon_status_url",\
							"kind": "function"\
						},\
						{\
							"name": "to_mastodon_status_url_with_author",\
							"kind": "function"\
						},\
						{\
							"name": "to_mastodon_status_url_with_users_author",\
							"kind": "function"\
						},\
						{\
							"name": "to_mastodon_api_status_url",\
							"kind": "function"\
						},\
						{\
							"name": "to_mastodon_api_status_context_url",\
							"kind": "function"\
						},\
						{\
							"name": "to_mastodon_api_favourites_url",\
							"kind": "function"\
						},\
						{\
							"name": "Mastodon_Status_Url",\
							"kind": "type"\
						},\
						{\
							"name": "parse_mastodon_status_url",\
							"kind": "function"\
						},\
						{\
							"name": "fetch_mastodon_status_context",\
							"kind": "function"\
						},\
						{\
							"name": "fetch_mastodon_status",\
							"kind": "function"\
						},\
						{\
							"name": "fetch_mastodon_favourites",\
							"kind": "function"\
						},\
						{\
							"name": "Mastodon_Status_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Mastodon_Status",\
							"kind": "type"\
						},\
						{\
							"name": "Mastodon_Favourite",\
							"kind": "type"\
						},\
						{\
							"name": "Reply_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "Favourited_By_Reply_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "Minimum_Favourites_Reply_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "Custom_Reply_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Reply_Filters",\
							"kind": "type"\
						},\
						{\
							"name": "filter_valid_replies",\
							"kind": "function"\
						}\
					]\
				},\
				"./storage.js": {\
					"path": "storage.ts",\
					"declarations": [\
						{\
							"name": "load_from_storage",\
							"kind": "function"\
						},\
						{\
							"name": "set_in_storage",\
							"kind": "function"\
						}\
					]\
				},\
				"./Mastodon_Status_Item.svelte": {\
					"path": "Mastodon_Status_Item.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Mastodon_Status_Tree.svelte": {\
					"path": "Mastodon_Status_Tree.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Toot_Input.svelte": {\
					"path": "Toot_Input.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Toot_Loader.svelte": {\
					"path": "Toot_Loader.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				},\
				"./Toot.svelte": {\
					"path": "Toot.svelte",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "component"\
						}\
					]\
				}\
			}\
		},\
		"name": "@ryanatkn/fuz_mastodon",\
		"repo_name": "fuz_mastodon",\
		"repo_url": "https://github.com/ryanatkn/fuz_mastodon",\
		"owner_name": "ryanatkn",\
		"homepage_url": "https://mastodon.fuz.dev/",\
		"logo_url": "https://mastodon.fuz.dev/logo.svg",\
		"logo_alt": "a friendly purple spider facing you",\
		"npm_url": "https://www.npmjs.com/package/@ryanatkn/fuz_mastodon",\
		"changelog_url": "https://github.com/ryanatkn/fuz_mastodon/blob/main/CHANGELOG.md",\
		"published": true,\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	},\
	{\
		"package_json": {\
			"name": "@ryanatkn/gro",\
			"version": "0.167.1",\
			"description": "task runner and toolkit extending SvelteKit",\
			"motto": "generate, run, optimize",\
			"glyph": "🌰",\
			"logo": "logo.svg",\
			"logo_alt": "a pixelated green oak acorn with a glint of sun",\
			"public": true,\
			"license": "MIT",\
			"homepage": "https://gro.ryanatkn.com/",\
			"author": {\
				"name": "Ryan Atkinson",\
				"email": "mail@ryanatkn.com",\
				"url": "https://www.ryanatkn.com/"\
			},\
			"repository": {\
				"type": "git",\
				"url": "git+https://github.com/ryanatkn/gro.git"\
			},\
			"bugs": "https://github.com/ryanatkn/gro/issues",\
			"funding": "https://www.ryanatkn.com/funding",\
			"scripts": {\
				"bootstrap": "rm -rf .gro dist && svelte-kit sync && svelte-package && chmod +x ./dist/gro.js && npm link -f",\
				"start": "gro dev",\
				"dev": "gro dev",\
				"build": "gro build",\
				"check": "gro check",\
				"test": "gro test",\
				"preview": "vite preview",\
				"deploy": "gro deploy"\
			},\
			"type": "module",\
			"engines": {\
				"node": ">=22.15"\
			},\
			"bin": {\
				"gro": "dist/gro.js"\
			},\
			"keywords": [\
				"web",\
				"tools",\
				"task runner",\
				"tasks",\
				"codegen",\
				"svelte",\
				"sveltekit",\
				"vite",\
				"typescript"\
			],\
			"dependencies": {\
				"@ryanatkn/belt": "^0.34.1",\
				"chokidar": "^4.0.3",\
				"dotenv": "^17.2.2",\
				"esm-env": "^1.2.2",\
				"mri": "^1.2.0",\
				"oxc-parser": "^0.87.0",\
				"prettier": "^3.6.2",\
				"prettier-plugin-svelte": "^3.4.0",\
				"ts-blank-space": "^0.6.2",\
				"tslib": "^2.8.1",\
				"zod": "^4.1.5"\
			},\
			"peerDependencies": {\
				"@sveltejs/kit": "^2",\
				"esbuild": "^0.25",\
				"svelte": "^5",\
				"typescript": "^5",\
				"vitest": "^3"\
			},\
			"peerDependenciesMeta": {\
				"@sveltejs/kit": {\
					"optional": true\
				},\
				"vitest": {\
					"optional": true\
				}\
			},\
			"optionalDependencies": {\
				"vitest": "^3"\
			},\
			"devDependencies": {\
				"@changesets/changelog-git": "^0.2.1",\
				"@changesets/types": "^6.1.0",\
				"@ryanatkn/eslint-config": "^0.8.0",\
				"@ryanatkn/fuz": "^0.147.0",\
				"@ryanatkn/moss": "^0.36.0",\
				"@sveltejs/adapter-static": "^3.0.9",\
				"@sveltejs/kit": "^2.37.1",\
				"@sveltejs/package": "^2.5.0",\
				"@sveltejs/vite-plugin-svelte": "^6.1.4",\
				"@types/node": "^24.3.1",\
				"esbuild": "^0.25.9",\
				"eslint": "^9.35.0",\
				"eslint-plugin-svelte": "^3.12.2",\
				"svelte": "^5.38.7",\
				"svelte-check": "^4.3.2",\
				"typescript": "^5.9.2",\
				"typescript-eslint": "^8.42.0",\
				"vitest": "^3.2.4"\
			},\
			"prettier": {\
				"plugins": [\
					"prettier-plugin-svelte"\
				],\
				"useTabs": true,\
				"printWidth": 100,\
				"singleQuote": true,\
				"bracketSpacing": false,\
				"overrides": [\
					{\
						"files": "package.json",\
						"options": {\
							"useTabs": false\
						}\
					}\
				]\
			},\
			"sideEffects": [\
				"**/*.css"\
			],\
			"files": [\
				"dist",\
				"src/lib/**/*.ts",\
				"!src/lib/**/*.test.*",\
				"!dist/**/*.test.*"\
			],\
			"exports": {\
				"./package.json": "./package.json",\
				".": {\
					"types": "./dist/index.d.ts",\
					"default": "./dist/index.js"\
				},\
				"./*.js": {\
					"types": "./dist/*.d.ts",\
					"default": "./dist/*.js"\
				}\
			}\
		},\
		"src_json": {\
			"name": "@ryanatkn/gro",\
			"version": "0.167.1",\
			"modules": {\
				".": {\
					"path": "index.ts",\
					"declarations": [\
						{\
							"name": "Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Plugin",\
							"kind": "type"\
						},\
						{\
							"name": "replace_plugin",\
							"kind": "function"\
						},\
						{\
							"name": "Gen",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Task",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Error",\
							"kind": "class"\
						}\
					]\
				},\
				"./args.js": {\
					"path": "args.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "type"\
						},\
						{\
							"name": "Arg_Value",\
							"kind": "type"\
						},\
						{\
							"name": "Arg_Schema",\
							"kind": "type"\
						},\
						{\
							"name": "parse_args",\
							"kind": "function"\
						},\
						{\
							"name": "serialize_args",\
							"kind": "function"\
						},\
						{\
							"name": "to_task_args",\
							"kind": "function"\
						},\
						{\
							"name": "to_raw_rest_args",\
							"kind": "function"\
						},\
						{\
							"name": "to_forwarded_args",\
							"kind": "function"\
						},\
						{\
							"name": "to_forwarded_args_by_command",\
							"kind": "function"\
						},\
						{\
							"name": "print_command_args",\
							"kind": "function"\
						}\
					]\
				},\
				"./build.task.js": {\
					"path": "build.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./changelog.js": {\
					"path": "changelog.ts",\
					"declarations": [\
						{\
							"name": "update_changelog",\
							"kind": "function"\
						}\
					]\
				},\
				"./changeset_helpers.js": {\
					"path": "changeset_helpers.ts",\
					"declarations": [\
						{\
							"name": "CHANGESET_RESTRICTED_ACCESS",\
							"kind": "variable"\
						},\
						{\
							"name": "CHANGESET_PUBLIC_ACCESS",\
							"kind": "variable"\
						},\
						{\
							"name": "Changeset_Access",\
							"kind": "variable"\
						},\
						{\
							"name": "CHANGESET_CLI",\
							"kind": "variable"\
						},\
						{\
							"name": "CHANGESET_DIR",\
							"kind": "variable"\
						},\
						{\
							"name": "Changeset_Bump",\
							"kind": "variable"\
						}\
					]\
				},\
				"./changeset.task.js": {\
					"path": "changeset.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./check.task.js": {\
					"path": "check.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./child_process_logging.js": {\
					"path": "child_process_logging.ts",\
					"declarations": [\
						{\
							"name": "map_child_process_output",\
							"kind": "function"\
						},\
						{\
							"name": "configure_colored_output_with_path_replacement",\
							"kind": "function"\
						}\
					]\
				},\
				"./clean_fs.js": {\
					"path": "clean_fs.ts",\
					"declarations": [\
						{\
							"name": "clean_fs",\
							"kind": "function"\
						}\
					]\
				},\
				"./clean.task.js": {\
					"path": "clean.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./cli.js": {\
					"path": "cli.ts",\
					"declarations": [\
						{\
							"name": "Cli",\
							"kind": "type"\
						},\
						{\
							"name": "find_cli",\
							"kind": "function"\
						},\
						{\
							"name": "spawn_cli",\
							"kind": "function"\
						},\
						{\
							"name": "spawn_cli_process",\
							"kind": "function"\
						},\
						{\
							"name": "resolve_cli",\
							"kind": "function"\
						},\
						{\
							"name": "to_cli_name",\
							"kind": "function"\
						}\
					]\
				},\
				"./commit.task.js": {\
					"path": "commit.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./constants.js": {\
					"path": "constants.ts",\
					"declarations": [\
						{\
							"name": "SOURCE_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_DIST_PREFIX",\
							"kind": "variable"\
						},\
						{\
							"name": "SERVER_DIST_PATH",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_DEV_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SOURCE_DIR",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_DIR",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_DEV_DIR",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_CONFIG_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "README_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_CONFIG_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "VITE_CONFIG_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "NODE_MODULES_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "PACKAGE_JSON_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "LOCKFILE_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_DEV_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_BUILD_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_DIST_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_VITE_CACHE_PATH",\
							"kind": "variable"\
						},\
						{\
							"name": "GITHUB_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "GIT_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "TSCONFIG_FILENAME",\
							"kind": "variable"\
						},\
						{\
							"name": "TS_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "JS_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "JSON_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_RUNES_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "CSS_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_SCRIPT_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_ENV_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_GLOBAL_SPECIFIER",\
							"kind": "variable"\
						},\
						{\
							"name": "EVERYTHING_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "JS_CLI_DEFAULT",\
							"kind": "variable"\
						},\
						{\
							"name": "PM_CLI_DEFAULT",\
							"kind": "variable"\
						},\
						{\
							"name": "PRETTIER_CLI_DEFAULT",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_CLI",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_CHECK_CLI",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_PACKAGE_CLI",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTE_PACKAGE_DEP_NAME",\
							"kind": "variable"\
						},\
						{\
							"name": "VITE_CLI",\
							"kind": "variable"\
						},\
						{\
							"name": "VITEST_CLI",\
							"kind": "variable"\
						}\
					]\
				},\
				"./deploy.task.js": {\
					"path": "deploy.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./dev.task.js": {\
					"path": "dev.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "DevTask_Context",\
							"kind": "type"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./disknode.js": {\
					"path": "disknode.ts",\
					"declarations": [\
						{\
							"name": "Disknode",\
							"kind": "type"\
						}\
					]\
				},\
				"./env.js": {\
					"path": "env.ts",\
					"declarations": [\
						{\
							"name": "load_env",\
							"kind": "function"\
						},\
						{\
							"name": "merge_envs",\
							"kind": "function"\
						},\
						{\
							"name": "is_private_env",\
							"kind": "function"\
						},\
						{\
							"name": "is_public_env",\
							"kind": "function"\
						},\
						{\
							"name": "load_from_env",\
							"kind": "function"\
						}\
					]\
				},\
				"./esbuild_helpers.js": {\
					"path": "esbuild_helpers.ts",\
					"declarations": [\
						{\
							"name": "print_build_result",\
							"kind": "function"\
						},\
						{\
							"name": "to_define_import_meta_env",\
							"kind": "function"\
						},\
						{\
							"name": "default_ts_transform_options",\
							"kind": "variable"\
						}\
					]\
				},\
				"./esbuild_plugin_external_worker.js": {\
					"path": "esbuild_plugin_external_worker.ts",\
					"declarations": [\
						{\
							"name": "Esbuild_Plugin_External_Worker_Options",\
							"kind": "type"\
						},\
						{\
							"name": "esbuild_plugin_external_worker",\
							"kind": "function"\
						}\
					]\
				},\
				"./esbuild_plugin_svelte.js": {\
					"path": "esbuild_plugin_svelte.ts",\
					"declarations": [\
						{\
							"name": "Esbuild_Plugin_Svelte_Options",\
							"kind": "type"\
						},\
						{\
							"name": "esbuild_plugin_svelte",\
							"kind": "function"\
						}\
					]\
				},\
				"./esbuild_plugin_sveltekit_local_imports.js": {\
					"path": "esbuild_plugin_sveltekit_local_imports.ts",\
					"declarations": [\
						{\
							"name": "esbuild_plugin_sveltekit_local_imports",\
							"kind": "function"\
						}\
					]\
				},\
				"./esbuild_plugin_sveltekit_shim_alias.js": {\
					"path": "esbuild_plugin_sveltekit_shim_alias.ts",\
					"declarations": [\
						{\
							"name": "Esbuild_Plugin_Sveltekit_Shim_Alias_Options",\
							"kind": "type"\
						},\
						{\
							"name": "esbuild_plugin_sveltekit_shim_alias",\
							"kind": "function"\
						}\
					]\
				},\
				"./esbuild_plugin_sveltekit_shim_app.js": {\
					"path": "esbuild_plugin_sveltekit_shim_app.ts",\
					"declarations": [\
						{\
							"name": "Esbuild_Plugin_Sveltekit_Shim_App_Options",\
							"kind": "type"\
						},\
						{\
							"name": "esbuild_plugin_sveltekit_shim_app",\
							"kind": "function"\
						}\
					]\
				},\
				"./esbuild_plugin_sveltekit_shim_env.js": {\
					"path": "esbuild_plugin_sveltekit_shim_env.ts",\
					"declarations": [\
						{\
							"name": "Esbuild_Plugin_Sveltekit_Shim_Env_Options",\
							"kind": "type"\
						},\
						{\
							"name": "esbuild_plugin_sveltekit_shim_env",\
							"kind": "function"\
						}\
					]\
				},\
				"./filer.js": {\
					"path": "filer.ts",\
					"declarations": [\
						{\
							"name": "On_Filer_Change",\
							"kind": "type"\
						},\
						{\
							"name": "Filer_Options",\
							"kind": "type"\
						},\
						{\
							"name": "Filer",\
							"kind": "class"\
						},\
						{\
							"name": "filter_dependents",\
							"kind": "function"\
						}\
					]\
				},\
				"./format_directory.js": {\
					"path": "format_directory.ts",\
					"declarations": [\
						{\
							"name": "format_directory",\
							"kind": "function"\
						}\
					]\
				},\
				"./format_file.js": {\
					"path": "format_file.ts",\
					"declarations": [\
						{\
							"name": "format_file",\
							"kind": "function"\
						}\
					]\
				},\
				"./format.task.js": {\
					"path": "format.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./fs.js": {\
					"path": "fs.ts",\
					"declarations": [\
						{\
							"name": "empty_dir",\
							"kind": "function"\
						}\
					]\
				},\
				"./gen_helpers.js": {\
					"path": "gen_helpers.ts",\
					"declarations": [\
						{\
							"name": "should_trigger_gen",\
							"kind": "function"\
						}\
					]\
				},\
				"./gen.task.js": {\
					"path": "gen.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./gen.js": {\
					"path": "gen.ts",\
					"declarations": [\
						{\
							"name": "GEN_FILE_PATTERN_TEXT",\
							"kind": "variable"\
						},\
						{\
							"name": "GEN_FILE_PATTERN",\
							"kind": "variable"\
						},\
						{\
							"name": "is_gen_path",\
							"kind": "function"\
						},\
						{\
							"name": "Gen_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_File",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Dependencies",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Dependencies_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Dependencies_Resolver",\
							"kind": "type"\
						},\
						{\
							"name": "Gen",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Function",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gen_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gen_File",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Results",\
							"kind": "type"\
						},\
						{\
							"name": "Genfile_Module_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Genfile_Module_Result_Success",\
							"kind": "type"\
						},\
						{\
							"name": "Genfile_Module_Result_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "to_gen_result",\
							"kind": "function"\
						},\
						{\
							"name": "to_output_file_name",\
							"kind": "function"\
						},\
						{\
							"name": "Analyzed_Gen_Result",\
							"kind": "type"\
						},\
						{\
							"name": "analyze_gen_results",\
							"kind": "function"\
						},\
						{\
							"name": "analyze_gen_result",\
							"kind": "function"\
						},\
						{\
							"name": "write_gen_results",\
							"kind": "function"\
						},\
						{\
							"name": "Found_Genfiles",\
							"kind": "type"\
						},\
						{\
							"name": "Find_Genfiles_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Find_Genfiles_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "find_genfiles",\
							"kind": "function"\
						},\
						{\
							"name": "Genfile_Module",\
							"kind": "type"\
						},\
						{\
							"name": "Genfile_Module_Meta",\
							"kind": "type"\
						},\
						{\
							"name": "Loaded_Genfiles",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Genfiles_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Genfiles_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "load_genfiles",\
							"kind": "function"\
						},\
						{\
							"name": "validate_gen_module",\
							"kind": "function"\
						},\
						{\
							"name": "normalize_gen_config",\
							"kind": "function"\
						}\
					]\
				},\
				"./git.js": {\
					"path": "git.ts",\
					"declarations": [\
						{\
							"name": "Git_Origin",\
							"kind": "variable"\
						},\
						{\
							"name": "Git_Branch",\
							"kind": "variable"\
						},\
						{\
							"name": "git_current_branch_name",\
							"kind": "function"\
						},\
						{\
							"name": "git_remote_branch_exists",\
							"kind": "function"\
						},\
						{\
							"name": "git_local_branch_exists",\
							"kind": "function"\
						},\
						{\
							"name": "git_check_clean_workspace",\
							"kind": "function"\
						},\
						{\
							"name": "git_check_fully_staged_workspace",\
							"kind": "function"\
						},\
						{\
							"name": "git_fetch",\
							"kind": "function"\
						},\
						{\
							"name": "git_checkout",\
							"kind": "function"\
						},\
						{\
							"name": "git_pull",\
							"kind": "function"\
						},\
						{\
							"name": "git_push",\
							"kind": "function"\
						},\
						{\
							"name": "git_push_to_create",\
							"kind": "function"\
						},\
						{\
							"name": "git_delete_local_branch",\
							"kind": "function"\
						},\
						{\
							"name": "git_delete_remote_branch",\
							"kind": "function"\
						},\
						{\
							"name": "git_reset_branch_to_first_commit",\
							"kind": "function"\
						},\
						{\
							"name": "git_current_commit_hash",\
							"kind": "function"\
						},\
						{\
							"name": "git_current_branch_first_commit_hash",\
							"kind": "function"\
						},\
						{\
							"name": "git_check_setting_pull_rebase",\
							"kind": "function"\
						},\
						{\
							"name": "git_clone_locally",\
							"kind": "function"\
						}\
					]\
				},\
				"./github.js": {\
					"path": "github.ts",\
					"declarations": [\
						{\
							"name": "GITHUB_REPO_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "Github_Pull_Request",\
							"kind": "variable"\
						},\
						{\
							"name": "github_fetch_commit_prs",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro_config.js": {\
					"path": "gro_config.ts",\
					"declarations": [\
						{\
							"name": "Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "create_empty_gro_config",\
							"kind": "function"\
						},\
						{\
							"name": "SEARCH_EXCLUDER_DEFAULT",\
							"kind": "variable"\
						},\
						{\
							"name": "EXPORTS_EXCLUDER_DEFAULT",\
							"kind": "variable"\
						},\
						{\
							"name": "cook_gro_config",\
							"kind": "function"\
						},\
						{\
							"name": "Gro_Config_Module",\
							"kind": "type"\
						},\
						{\
							"name": "load_gro_config",\
							"kind": "function"\
						},\
						{\
							"name": "validate_gro_config_module",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro_helpers.js": {\
					"path": "gro_helpers.ts",\
					"declarations": [\
						{\
							"name": "resolve_gro_module_path",\
							"kind": "function"\
						},\
						{\
							"name": "spawn_with_loader",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro_plugin_gen.js": {\
					"path": "gro_plugin_gen.ts",\
					"declarations": [\
						{\
							"name": "Task_Args",\
							"kind": "type"\
						},\
						{\
							"name": "Gro_Plugin_Gen_Options",\
							"kind": "type"\
						},\
						{\
							"name": "gro_plugin_gen",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro_plugin_server.js": {\
					"path": "gro_plugin_server.ts",\
					"declarations": [\
						{\
							"name": "SERVER_SOURCE_ID",\
							"kind": "variable"\
						},\
						{\
							"name": "has_server",\
							"kind": "function"\
						},\
						{\
							"name": "Gro_Plugin_Server_Options",\
							"kind": "type"\
						},\
						{\
							"name": "Outpaths",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Outpaths",\
							"kind": "type"\
						},\
						{\
							"name": "gro_plugin_server",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro_plugin_sveltekit_app.js": {\
					"path": "gro_plugin_sveltekit_app.ts",\
					"declarations": [\
						{\
							"name": "Gro_Plugin_Sveltekit_App_Options",\
							"kind": "type"\
						},\
						{\
							"name": "Host_Target",\
							"kind": "type"\
						},\
						{\
							"name": "Copy_File_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "gro_plugin_sveltekit_app",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro_plugin_sveltekit_library.js": {\
					"path": "gro_plugin_sveltekit_library.ts",\
					"declarations": [\
						{\
							"name": "Gro_Plugin_Sveltekit_Library_Options",\
							"kind": "type"\
						},\
						{\
							"name": "gro_plugin_sveltekit_library",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro.config.default.js": {\
					"path": "gro.config.default.ts",\
					"declarations": [\
						{\
							"name": "default",\
							"kind": "function"\
						}\
					]\
				},\
				"./gro.js": {\
					"path": "gro.ts"\
				},\
				"./hash.js": {\
					"path": "hash.ts",\
					"declarations": [\
						{\
							"name": "to_hash",\
							"kind": "function"\
						}\
					]\
				},\
				"./index.js": {\
					"path": "index.ts",\
					"declarations": [\
						{\
							"name": "Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Raw_Gro_Config",\
							"kind": "type"\
						},\
						{\
							"name": "Plugin",\
							"kind": "type"\
						},\
						{\
							"name": "replace_plugin",\
							"kind": "function"\
						},\
						{\
							"name": "Gen",\
							"kind": "type"\
						},\
						{\
							"name": "Gen_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Task",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Error",\
							"kind": "class"\
						}\
					]\
				},\
				"./input_path.js": {\
					"path": "input_path.ts",\
					"declarations": [\
						{\
							"name": "Input_Path",\
							"kind": "variable"\
						},\
						{\
							"name": "Raw_Input_Path",\
							"kind": "variable"\
						},\
						{\
							"name": "to_input_path",\
							"kind": "function"\
						},\
						{\
							"name": "to_input_paths",\
							"kind": "function"\
						},\
						{\
							"name": "Possible_Path",\
							"kind": "type"\
						},\
						{\
							"name": "get_possible_paths",\
							"kind": "function"\
						},\
						{\
							"name": "Resolved_Input_Path",\
							"kind": "type"\
						},\
						{\
							"name": "Resolved_Input_File",\
							"kind": "type"\
						},\
						{\
							"name": "Resolved_Input_Paths",\
							"kind": "type"\
						},\
						{\
							"name": "resolve_input_paths",\
							"kind": "function"\
						},\
						{\
							"name": "Resolved_Input_Files",\
							"kind": "type"\
						},\
						{\
							"name": "resolve_input_files",\
							"kind": "function"\
						}\
					]\
				},\
				"./invoke_task.js": {\
					"path": "invoke_task.ts",\
					"declarations": [\
						{\
							"name": "invoke_task",\
							"kind": "function"\
						}\
					]\
				},\
				"./invoke.js": {\
					"path": "invoke.ts"\
				},\
				"./lint.task.js": {\
					"path": "lint.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./loader.js": {\
					"path": "loader.ts",\
					"declarations": [\
						{\
							"name": "load",\
							"kind": "function"\
						},\
						{\
							"name": "resolve",\
							"kind": "function"\
						}\
					]\
				},\
				"./module.js": {\
					"path": "module.ts",\
					"declarations": [\
						{\
							"name": "MODULE_PATH_SRC_PREFIX",\
							"kind": "variable"\
						},\
						{\
							"name": "MODULE_PATH_LIB_PREFIX",\
							"kind": "variable"\
						},\
						{\
							"name": "is_external_module",\
							"kind": "function"\
						}\
					]\
				},\
				"./modules.js": {\
					"path": "modules.ts",\
					"declarations": [\
						{\
							"name": "Module_Meta",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Module_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Module_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "load_module",\
							"kind": "function"\
						},\
						{\
							"name": "Load_Modules_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Modules_Result",\
							"kind": "type"\
						},\
						{\
							"name": "load_modules",\
							"kind": "function"\
						}\
					]\
				},\
				"./package_json.js": {\
					"path": "package_json.ts",\
					"declarations": [\
						{\
							"name": "Map_Package_Json",\
							"kind": "type"\
						},\
						{\
							"name": "EMPTY_PACKAGE_JSON",\
							"kind": "variable"\
						},\
						{\
							"name": "load_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "sync_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "load_gro_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "write_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "serialize_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "update_package_json",\
							"kind": "function"\
						},\
						{\
							"name": "to_package_exports",\
							"kind": "function"\
						},\
						{\
							"name": "parse_repo_url",\
							"kind": "function"\
						},\
						{\
							"name": "has_dep",\
							"kind": "function"\
						},\
						{\
							"name": "Package_Json_Dep",\
							"kind": "type"\
						},\
						{\
							"name": "extract_deps",\
							"kind": "function"\
						}\
					]\
				},\
				"./package.gen.js": {\
					"path": "package.gen.ts",\
					"declarations": [\
						{\
							"name": "gen",\
							"kind": "function"\
						}\
					]\
				},\
				"./package.js": {\
					"path": "package.ts",\
					"declarations": [\
						{\
							"name": "package_json",\
							"kind": "variable"\
						},\
						{\
							"name": "src_json",\
							"kind": "variable"\
						}\
					]\
				},\
				"./parse_exports_context.js": {\
					"path": "parse_exports_context.ts",\
					"declarations": [\
						{\
							"name": "Parse_Exports_Context",\
							"kind": "class"\
						}\
					]\
				},\
				"./parse_exports.js": {\
					"path": "parse_exports.ts",\
					"declarations": [\
						{\
							"name": "Declaration",\
							"kind": "type"\
						},\
						{\
							"name": "Export_Declaration",\
							"kind": "type"\
						},\
						{\
							"name": "parse_exports",\
							"kind": "function"\
						},\
						{\
							"name": "infer_declarations_from_file_type",\
							"kind": "function"\
						},\
						{\
							"name": "process_ts_exports",\
							"kind": "function"\
						}\
					]\
				},\
				"./parse_imports.js": {\
					"path": "parse_imports.ts",\
					"declarations": [\
						{\
							"name": "Import_Specifier",\
							"kind": "type"\
						},\
						{\
							"name": "parse_imports",\
							"kind": "function"\
						}\
					]\
				},\
				"./path.js": {\
					"path": "path.ts",\
					"declarations": [\
						{\
							"name": "Path_Id",\
							"kind": "type"\
						},\
						{\
							"name": "Path_Info",\
							"kind": "type"\
						},\
						{\
							"name": "Resolved_Path",\
							"kind": "type"\
						},\
						{\
							"name": "Path_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "File_Filter",\
							"kind": "type"\
						},\
						{\
							"name": "to_file_path",\
							"kind": "function"\
						}\
					]\
				},\
				"./paths.js": {\
					"path": "paths.ts",\
					"declarations": [\
						{\
							"name": "LIB_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "LIB_PATH",\
							"kind": "variable"\
						},\
						{\
							"name": "LIB_DIR",\
							"kind": "variable"\
						},\
						{\
							"name": "ROUTES_DIRNAME",\
							"kind": "variable"\
						},\
						{\
							"name": "Paths",\
							"kind": "type"\
						},\
						{\
							"name": "create_paths",\
							"kind": "function"\
						},\
						{\
							"name": "infer_paths",\
							"kind": "function"\
						},\
						{\
							"name": "is_gro_id",\
							"kind": "function"\
						},\
						{\
							"name": "to_root_path",\
							"kind": "function"\
						},\
						{\
							"name": "path_id_to_base_path",\
							"kind": "function"\
						},\
						{\
							"name": "base_path_to_path_id",\
							"kind": "function"\
						},\
						{\
							"name": "print_path",\
							"kind": "function"\
						},\
						{\
							"name": "replace_extension",\
							"kind": "function"\
						},\
						{\
							"name": "paths",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_PACKAGE_DIR",\
							"kind": "variable"\
						},\
						{\
							"name": "IS_THIS_GRO",\
							"kind": "variable"\
						},\
						{\
							"name": "gro_paths",\
							"kind": "variable"\
						},\
						{\
							"name": "GRO_DIST_DIR",\
							"kind": "variable"\
						}\
					]\
				},\
				"./plugin.js": {\
					"path": "plugin.ts",\
					"declarations": [\
						{\
							"name": "Plugin",\
							"kind": "type"\
						},\
						{\
							"name": "Create_Config_Plugins",\
							"kind": "type"\
						},\
						{\
							"name": "Plugin_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Plugins",\
							"kind": "class"\
						},\
						{\
							"name": "replace_plugin",\
							"kind": "function"\
						}\
					]\
				},\
				"./publish.task.js": {\
					"path": "publish.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./register.js": {\
					"path": "register.ts"\
				},\
				"./reinstall.task.js": {\
					"path": "reinstall.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./release.task.js": {\
					"path": "release.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./resolve_specifier.js": {\
					"path": "resolve_specifier.ts",\
					"declarations": [\
						{\
							"name": "Resolved_Specifier",\
							"kind": "type"\
						},\
						{\
							"name": "resolve_specifier",\
							"kind": "function"\
						}\
					]\
				},\
				"./resolve.task.js": {\
					"path": "resolve.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./run_gen.js": {\
					"path": "run_gen.ts",\
					"declarations": [\
						{\
							"name": "GEN_NO_PROD_MESSAGE",\
							"kind": "variable"\
						},\
						{\
							"name": "run_gen",\
							"kind": "function"\
						}\
					]\
				},\
				"./run_task.js": {\
					"path": "run_task.ts",\
					"declarations": [\
						{\
							"name": "Run_Task_Result",\
							"kind": "type"\
						},\
						{\
							"name": "run_task",\
							"kind": "function"\
						}\
					]\
				},\
				"./run.task.js": {\
					"path": "run.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./search_fs.js": {\
					"path": "search_fs.ts",\
					"declarations": [\
						{\
							"name": "Search_Fs_Options",\
							"kind": "type"\
						},\
						{\
							"name": "search_fs",\
							"kind": "function"\
						},\
						{\
							"name": "find_first_existing_file",\
							"kind": "function"\
						}\
					]\
				},\
				"./src_json.js": {\
					"path": "src_json.ts",\
					"declarations": [\
						{\
							"name": "Map_Src_Json",\
							"kind": "type"\
						},\
						{\
							"name": "create_src_json",\
							"kind": "function"\
						},\
						{\
							"name": "serialize_src_json",\
							"kind": "function"\
						},\
						{\
							"name": "to_src_modules",\
							"kind": "function"\
						}\
					]\
				},\
				"./svelte_config.js": {\
					"path": "svelte_config.ts",\
					"declarations": [\
						{\
							"name": "load_svelte_config",\
							"kind": "function"\
						},\
						{\
							"name": "Parsed_Svelte_Config",\
							"kind": "type"\
						},\
						{\
							"name": "parse_svelte_config",\
							"kind": "function"\
						},\
						{\
							"name": "to_default_compile_module_options",\
							"kind": "function"\
						},\
						{\
							"name": "default_svelte_config",\
							"kind": "variable"\
						}\
					]\
				},\
				"./sveltekit_helpers.js": {\
					"path": "sveltekit_helpers.ts",\
					"declarations": [\
						{\
							"name": "has_sveltekit_app",\
							"kind": "function"\
						},\
						{\
							"name": "has_sveltekit_library",\
							"kind": "function"\
						},\
						{\
							"name": "sveltekit_sync",\
							"kind": "function"\
						},\
						{\
							"name": "sveltekit_sync_if_available",\
							"kind": "function"\
						},\
						{\
							"name": "sveltekit_sync_if_obviously_needed",\
							"kind": "function"\
						},\
						{\
							"name": "Svelte_Package_Options",\
							"kind": "type"\
						},\
						{\
							"name": "run_svelte_package",\
							"kind": "function"\
						},\
						{\
							"name": "map_sveltekit_aliases",\
							"kind": "function"\
						}\
					]\
				},\
				"./sveltekit_shim_app_environment.js": {\
					"path": "sveltekit_shim_app_environment.ts",\
					"declarations": [\
						{\
							"name": "browser",\
							"kind": "variable"\
						},\
						{\
							"name": "building",\
							"kind": "variable"\
						},\
						{\
							"name": "dev",\
							"kind": "variable"\
						},\
						{\
							"name": "version",\
							"kind": "variable"\
						}\
					]\
				},\
				"./sveltekit_shim_app_forms.js": {\
					"path": "sveltekit_shim_app_forms.ts",\
					"declarations": [\
						{\
							"name": "applyAction",\
							"kind": "function"\
						},\
						{\
							"name": "deserialize",\
							"kind": "function"\
						},\
						{\
							"name": "enhance",\
							"kind": "function"\
						}\
					]\
				},\
				"./sveltekit_shim_app_navigation.js": {\
					"path": "sveltekit_shim_app_navigation.ts",\
					"declarations": [\
						{\
							"name": "afterNavigate",\
							"kind": "function"\
						},\
						{\
							"name": "beforeNavigate",\
							"kind": "function"\
						},\
						{\
							"name": "disableScrollHandling",\
							"kind": "function"\
						},\
						{\
							"name": "goto",\
							"kind": "function"\
						},\
						{\
							"name": "invalidate",\
							"kind": "function"\
						},\
						{\
							"name": "invalidateAll",\
							"kind": "function"\
						},\
						{\
							"name": "preloadCode",\
							"kind": "function"\
						},\
						{\
							"name": "preloadData",\
							"kind": "function"\
						}\
					]\
				},\
				"./sveltekit_shim_app_paths.js": {\
					"path": "sveltekit_shim_app_paths.ts",\
					"declarations": [\
						{\
							"name": "assets",\
							"kind": "variable"\
						},\
						{\
							"name": "base",\
							"kind": "variable"\
						},\
						{\
							"name": "resolve",\
							"kind": "function"\
						},\
						{\
							"name": "resolveRoute",\
							"kind": "function"\
						},\
						{\
							"name": "asset",\
							"kind": "function"\
						}\
					]\
				},\
				"./sveltekit_shim_app_state.js": {\
					"path": "sveltekit_shim_app_state.ts",\
					"declarations": [\
						{\
							"name": "navigating",\
							"kind": "variable"\
						},\
						{\
							"name": "page",\
							"kind": "variable"\
						},\
						{\
							"name": "updated",\
							"kind": "variable"\
						}\
					]\
				},\
				"./sveltekit_shim_app.js": {\
					"path": "sveltekit_shim_app.ts",\
					"declarations": [\
						{\
							"name": "SVELTEKIT_SHIM_APP_PATHS_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "SVELTEKIT_SHIM_APP_ENVIRONMENT_MATCHER",\
							"kind": "variable"\
						},\
						{\
							"name": "sveltekit_shim_app_specifiers",\
							"kind": "variable"\
						},\
						{\
							"name": "render_sveltekit_shim_app_paths",\
							"kind": "function"\
						},\
						{\
							"name": "render_sveltekit_shim_app_environment",\
							"kind": "function"\
						}\
					]\
				},\
				"./sveltekit_shim_env.js": {\
					"path": "sveltekit_shim_env.ts",\
					"declarations": [\
						{\
							"name": "render_env_shim_module",\
							"kind": "function"\
						}\
					]\
				},\
				"./sync.task.js": {\
					"path": "sync.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./task_logging.js": {\
					"path": "task_logging.ts",\
					"declarations": [\
						{\
							"name": "log_tasks",\
							"kind": "function"\
						},\
						{\
							"name": "log_error_reasons",\
							"kind": "function"\
						},\
						{\
							"name": "log_task_help",\
							"kind": "function"\
						}\
					]\
				},\
				"./task.js": {\
					"path": "task.ts",\
					"declarations": [\
						{\
							"name": "Task",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Context",\
							"kind": "type"\
						},\
						{\
							"name": "Invoke_Task",\
							"kind": "type"\
						},\
						{\
							"name": "TASK_FILE_SUFFIX_TS",\
							"kind": "variable"\
						},\
						{\
							"name": "TASK_FILE_SUFFIX_JS",\
							"kind": "variable"\
						},\
						{\
							"name": "TASK_FILE_SUFFIXES",\
							"kind": "variable"\
						},\
						{\
							"name": "is_task_path",\
							"kind": "function"\
						},\
						{\
							"name": "to_task_name",\
							"kind": "function"\
						},\
						{\
							"name": "Task_Error",\
							"kind": "class"\
						},\
						{\
							"name": "Silent_Error",\
							"kind": "class"\
						},\
						{\
							"name": "Found_Task",\
							"kind": "type"\
						},\
						{\
							"name": "Found_Tasks",\
							"kind": "type"\
						},\
						{\
							"name": "Find_Tasks_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Find_Modules_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "find_tasks",\
							"kind": "function"\
						},\
						{\
							"name": "Loaded_Tasks",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Module",\
							"kind": "type"\
						},\
						{\
							"name": "Task_Module_Meta",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Tasks_Result",\
							"kind": "type"\
						},\
						{\
							"name": "Load_Tasks_Failure",\
							"kind": "type"\
						},\
						{\
							"name": "load_tasks",\
							"kind": "function"\
						},\
						{\
							"name": "validate_task_module",\
							"kind": "function"\
						}\
					]\
				},\
				"./test_helpers.js": {\
					"path": "test_helpers.ts",\
					"declarations": [\
						{\
							"name": "TEST_TIMEOUT_MD",\
							"kind": "variable"\
						},\
						{\
							"name": "SOME_PUBLIC_ENV_VAR_NAME",\
							"kind": "variable"\
						},\
						{\
							"name": "SOME_PUBLIC_ENV_VAR_VALUE",\
							"kind": "variable"\
						},\
						{\
							"name": "init_test_env",\
							"kind": "function"\
						},\
						{\
							"name": "create_ts_test_env",\
							"kind": "function"\
						}\
					]\
				},\
				"./test.task.js": {\
					"path": "test.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./typecheck.task.js": {\
					"path": "typecheck.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./upgrade.task.js": {\
					"path": "upgrade.task.ts",\
					"declarations": [\
						{\
							"name": "Args",\
							"kind": "variable"\
						},\
						{\
							"name": "task",\
							"kind": "variable"\
						}\
					]\
				},\
				"./watch_dir.js": {\
					"path": "watch_dir.ts",\
					"declarations": [\
						{\
							"name": "Watch_Node_Fs",\
							"kind": "type"\
						},\
						{\
							"name": "Watcher_Change",\
							"kind": "type"\
						},\
						{\
							"name": "Watcher_Change_Type",\
							"kind": "type"\
						},\
						{\
							"name": "Watcher_Change_Callback",\
							"kind": "type"\
						},\
						{\
							"name": "Watch_Dir_Options",\
							"kind": "type"\
						},\
						{\
							"name": "watch_dir",\
							"kind": "function"\
						}\
					]\
				}\
			}\
		},\
		"name": "@ryanatkn/gro",\
		"repo_name": "gro",\
		"repo_url": "https://github.com/ryanatkn/gro",\
		"owner_name": "ryanatkn",\
		"homepage_url": "https://gro.ryanatkn.com/",\
		"logo_url": "https://gro.ryanatkn.com/logo.svg",\
		"logo_alt": "a pixelated green oak acorn with a glint of sun",\
		"npm_url": "https://www.npmjs.com/package/@ryanatkn/gro",\
		"changelog_url": "https://github.com/ryanatkn/gro/blob/main/CHANGELOG.md",\
		"published": true,\
		"check_runs": {\
			"status": "completed",\
			"conclusion": "success"\
		},\
		"pull_requests": []\
	}\
]',
);
